# Markdownlint configuration
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
# Lenient configuration for academic/research content

# MD001/heading-increment - Heading levels should only increment by one level at a time
MD001: false

# MD007/ul-indent - Unordered list indentation
MD007: false

# MD009/no-trailing-spaces - Trailing spaces
MD009: false

# MD013/line-length - Line length - disable as academic papers often have long lines
MD013: false

# MD022/blanks-around-headings - Headings should be surrounded by blank lines
MD022: false

# MD024/no-duplicate-heading - Multiple headings with the same content
MD024:
  siblings_only: true

# MD025/single-title - Multiple top-level headings in the same document
MD025: false

# MD026/no-trailing-punctuation - Trailing punctuation in heading
MD026: false

# MD031/blanks-around-fences - Fenced code blocks should be surrounded by blank lines
MD031: false

# MD032/blanks-around-lists - Lists should be surrounded by blank lines
MD032: false

# MD033/no-inline-html - Inline HTML - allow for complex formatting in academic content
MD033: false

# MD034/no-bare-urls - Bare URL used - allow for reference lists
MD034: false

# MD036/no-emphasis-as-heading - Emphasis used instead of a heading
MD036: false

# MD040/fenced-code-language - Fenced code blocks should have a language specified
MD040: false

# MD041/first-line-heading - First line in file should be a top level heading
MD041: false

# MD046/code-block-style - Code block style
MD046:
  style: consistent

# MD047/single-trailing-newline - Files should end with a single newline character
MD047: false

# MD058/blanks-around-tables - Tables should be surrounded by blank lines
MD058: false

# MD060/table-column-style - Table column style
MD060: false
